import math
a,b = input().split()
a = int(a)
b = int(b)
print("The sum of a and b",a+b)
print("The difference a and b",a-b)
print("The product of a and b",a*b)
print("The quotient when a is divided by b",a//b)
print("The remainder when a is divided by b",a%b)
print("The result of log10a",math.log10(a))
print("The result of ab",str(a)+str(b))